sudo: required

before_install:
  - sudo echo "deb http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu quantal main" >> /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1DB8ADC1CFCA9579

  - sudo apt-get update -qq
  - sudo apt-get install -y -q wget curl build-essential cmake python2.7 python2.7-dev
# Don't think we need pip/numpy unless we want python bindings
#  - sudo wget 'https://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg' && /bin/sh setuptools-0.6c11-py2.7.egg && rm -f setuptools-0.6c11-py2.7.egg
#  - sudo curl 'https://raw.github.com/pypa/pip/master/contrib/get-pip.py' | python2.7
#  - sudo pip install numpy
  - sudo apt-get install -y -q libavformat-dev libavcodec-dev libavfilter-dev libswscale-dev
  - sudo apt-get install -y -q libjpeg-dev libpng-dev libtiff-dev libjasper-dev zlib1g-dev libopenexr-dev libxine-dev libeigen3-dev libtbb-dev


script:
  - /bin/sh -c "exit 0"