sudo: required

language: java

services:
  - docker

before_install:
  - docker build quebec-group/face .
#  - docker run -d -p 127.0.0.1:80:4567 quebec-group/face /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
#  - docker run quebec-group/face /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#  - bundle exec rake test